version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tmdb
      MYSQL_USER: tmdbuser
      MYSQL_PASSWORD: tmdbuser
    ports:
      - "3306:3306"
